---
- name: "create_param_control for {{ param.name }}"
  set_fact:
    create_param: "{{ lookup('aws_ssm', key_name ) }}"
  ignore_errors: true

- name: ssm create block
  block:
    - name: "add ssm parameter for {{ param.name}}"
      aws_ssm_parameter_store:
        name: "{{ key_name }}"
        description: "{{ description }}"
        string_type: "{{ key_type }}"
        value: "{{ key_value }}"
        overwrite_value: "{{ ssm_parameters.overwrite }}"
  when: ssm_parameters.overwrite != "never" or create_param == ''
