---
# tasks file for ssm_parameters
- name: "create user ssm_param_name fact {{ param.name }}"
  set_fact:
    ssm_param_name: "/{{ ssm_param_prefix }}/{{ param.name }}/{{ param.id }}"

- name: "create ssm entry for user password {{ param.name }}"
  include_tasks: create_password.yml
  vars:
    - character_set: "hexdigits"

- name: "create ssm entry secret {{ param.name }}"
  include_tasks: add_ssm_parameter.yml
  vars:
    key_name: "{{ ssm_param_name }}"
    key_type: "SecureString"
    key_value: "{{ password_value }}"
    description: "Ansible managed {{ ssm_param_name }} parameter"
