---
ssm_param_prefix: "cr-ancillary/jitbit"
ssm_parameters:
  overwrite: never
  passwords:
    - name: rds/database
      length: 20
      id: jitbit
    - name: rds/database/db
      length: 20
      id: admin
    - name: samba/share
      length: 15
      id: jitbit
    - name: system/common/user
      length: 15
      id: jitbit
  secrets:
    - name: samba/share
      length: 20
      id: password
    - name: ad/admin
      length: 15
      id: password
  sshkeys: []
