---
ssm_param_prefix: "cr-ancillary/jitbit"
ssm_parameters:
  overwrite: never
  passwords:
    - name: rds/database
      length: 20
      id: jitbit
    - name: rds/database/db
      length: 20
      id: admin
  secrets:
    - name: aws/storage/gateway
      length: 15
      id: guest
  sshkeys: []
