---
ssm_param_prefix: "cr-ancillary/jitbit"
ssm_parameters:
  overwrite: never
  passwords:
    # - name: rds/database
    #   length: 20
    #   id: jitbit
    # - name: rds/database/db
    #   length: 20
    #   id: admin
    # - name: system/common/user
    #   length: 15
    #   id: jitbit
    # - name: workmail
    #   length: 15
    #   id: office
  secrets:
    # - name: ad/admin
    #   length: 15
    #   id: password
  sshkeys: []
